[build]
builder = "NIXPACKS"
buildCommand = "npm ci --prefix backend"

[deploy]
startCommand = "npm --prefix backend start"
healthcheckPath = "/"
healthcheckTimeout = 120
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
